
-- CREATE TABLES
CREATE TABLE CONTROL_CLAVES (
	ID NUMBER NOT NULL,
	RUT VARCHAR2(15) NOT NULL,
	NUMERO_INTENTOS NUMBER(2) NOT NULL,
	FECHA_ACTUALIZACION DATE DEFAULT TO_DATE(SYSDATE, 'DD-MON-YYYY HH24:MI:SS') NOT NULL,
	ESTADO VARCHAR2(3) DEFAULT 'ACT' NOT NULL,
	PRIMARY KEY (ID)
);

-- CREATE SEQUENCES
--CREATE SEQUENCE SEQ_CONTROL_CLAVE_ID INCREMENT BY 1 START WITH 1;

-- CREATE TRIGGERS
--CREATE TRIGGER TRI_CONTROL_CLAVE_ID BEFORE INSERT ON CONTROL_CLAVE
--FOR EACH ROW
--BEGIN
--	SELECT SEQ_CONTROL_CLAVE_ID.NEXTVAL
--	INTO :NEW.ID
--	FROM DUAL;
--END;
